pipeline {
    agent any
    tools { 
      maven 'maven' 
      jdk 'java-11' 
    } 
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Compile') {
            steps {
                echo 'Job Complete!'
            }
        }
    }
}
